# Generated by Django 4.2.5 on 2023-11-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagefield',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
